AssignmentFujitsu_01_Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AssignmentFujitsu_01_Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AssignmentFujitsu_01_Web/Controllers/MasterSupplierController.cs
using AssignmentFujitsu_01_Web;
using AssignmentFujitsu_02_DataAccess;
using AssignmentFujitsu_03_ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AssignmentFujitsu_01_Web.Controllers
{
    public class MasterSupplierController : Controller
    {
        // GET: MasterSupplier
        public ActionResult Index()
        {
            ViewBag.PROVINCE = new SelectList(MasterSupplierDataAccess.GetListAll(),"SUPPLIER_CODE", "PROVINCE");
            ViewBag.CITY = new SelectList(MasterSupplierDataAccess.GetListAll(),"SUPPLIER_CODE", "CITY");
            return View();
        }


        public ActionResult Search(string paramSearch)
        {
            int countDataDb = MasterSupplierDataAccess.GetCountData(paramSearch);

            return PartialView("List", MasterSupplierDataAccess.GetListAll(paramSearch.ToLower()));
        }

        public ActionResult Create()
        {
            return PartialView();
        }

       
    }
}

AssignmentFujitsu_01_Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

@*<p>Use this area to provide additional information.</p>*@

AssignmentFujitsu_01_Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AssignmentFujitsu_01_Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AssignmentFujitsu_01_Web/Views/MasterSupplier/Index.cshtml
@model AssignmentFujitsu_03_ViewModel.MasterSupplierViewModel

@{ ViewBag.Title = "Index";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="color:red">Supplier Maintenance Screen</h4>
        <hr />
        
    <div class="row">
        <div class="w3-col l3 m3 s12">
            <label class="col-sm-2">Supplier Code</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.SUPPLIER_CODE, new { htmlAttributes = new { @class = "form-control", @style = "border:2px solid navy" } })
                @Html.ValidationMessageFor(model => model.SUPPLIER_CODE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="w3-col l2 m3 s6">
            <div style="padding-top: 10px">
                <button class="btn btn-danger" value="search" id="search">Search</button>
                <button class="btn btn-danger" value="reset">Clear</button>
            </div>
        </div>
        
    </div>
    <div class="row">
        <div class="w3-col l3 m3 s12" style="padding-top: 10px">
            <label class="col-sm-2">Province</label>
            <div class="col-sm-4">
                @Html.DropDownListFor(model => model.PROVINCE, (IEnumerable<SelectListItem>)ViewBag.PROVINCE, "- Pilih -", new { @class = "form-control", @style = "border:2px solid navy" })
                @Html.ValidationMessageFor(model => model.PROVINCE, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="w3-col l3 m3 s12" style="padding-top: 10px">
            <label class="col-sm-2">City</label>
            <div class="col-sm-4">
                @Html.DropDownListFor(model => model.CITY, (IEnumerable<SelectListItem>)ViewBag.CITY, "- Pilih -", new { @class = "form-control", @style = "border:2px solid navy" })
                @Html.ValidationMessageFor(model => model.CITY, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
        <hr />
        <hr />
        <div class="row">
            <div class="w3-col l3 m3 s12">
                <label class="col-sm-2">Choose File</label>
                <div class="col-sm-4">
                    <input type="file" name="pic" id="pic" />
                    @*@Html.EditorForm(model => model.PIC, new { htmlAttributes = new { @class = "form-control", @style = "border:2px solid navy" } })
                @Html.ValidationMessageFor(model => model.PIC, "", new { @class = "text-danger" })*@
                </div>
            </div>
            <div class="w3-col l2 m3 s8">
                <div style="padding-top: 10px">
                    <button class="btn btn-danger" value="add" id="add">Add</button>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div id="table-list" name="table-list">
            @Html.Partial("List")
        </div>
    </div>
    

    @section Scripts
    { 
        <script type="text/javascript">
            var ProgressHtml = '<div class="progress progress-striped active" style="margin-bottom:0"> <div class="progress-bar" style="width:100%"></div> </div>';

             $(document).ready(function () {
            ShowList();
        });

        function ShowList() {
            var vjs_search = $("#search").val();
            $("#table-list").html(ProgressHtml);

            $.ajax({
                url: '@Url.Action("List", "MasterSupplier")',
                type: 'get',
                data: {
                    paramSearch: vjs_search
                },
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        }    

            $("#add").click(function () {
            $
            })

        </script>
        }
}

AssignmentFujitsu_01_Web/Views/MasterSupplier/List.cshtml
@model IEnumerable<AssignmentFujitsu_03_ViewModel.MasterSupplierViewModel>

    <table style="background-color: aliceblue" ; width="100%">
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.SUPPLIER_CODE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SUPPLIER_NAME)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ADDRESS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PROVINCE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CITY)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PIC)
                    </td>
                </tr>
            }

        }

    </table>

AssignmentFujitsu_01_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>